const canvas=document.querySelector("#town"),ctx=canvas.getContext("2d");
const people=[
 {name:"Alice",role:"Reporter",skin:"#8c563b",hair:"#31221d",shirt:"#d85f49",skeptical:false,x:.18,y:.72,knows:true,believes:false},
 {name:"Bob",role:"Baker",skin:"#d59a73",hair:"#5b3827",shirt:"#e4a43c",skeptical:true,x:.38,y:.26,knows:false,believes:false},
 {name:"Charlie",role:"Librarian",skin:"#704733",hair:"#15171c",shirt:"#4776a8",skeptical:false,x:.70,y:.28,knows:false,believes:false},
 {name:"Dana",role:"Planner",skin:"#c68662",hair:"#7d3f4f",shirt:"#815b91",skeptical:true,x:.78,y:.72,knows:false,believes:false}
];
people.forEach(p=>Object.assign(p,{tx:p.x,ty:p.y,speech:"",bubbleUntil:0}));
const places=[["SUNRISE BAKERY",.06,.06,.27,.21,"#d88761"],["MAPLE LIBRARY",.67,.06,.27,.21,"#718bad"],["TOWN HALL",.06,.66,.27,.21,"#cdb15f"],["BUS STOP",.69,.69,.22,.14,"#6f9569"]];
const messages=[
 ["Bob, I heard your bakery is giving away free bread. Is that actually true?","I work there, and no giveaway was announced. Treat that rumor as unverified."],
 ["Alice said the bakery may have free bread.","I can mention it, but I do not know if it is true."],
 ["People are talking about a bakery giveaway.","I will remember it as an unverified report."]
];
const followUps=[
 ["Did anyone actually check with the bakery?","Not yet. We should not treat the rumor as confirmed."],
 ["The story has reached everyone in town.","Exposure does not necessarily mean belief."],
 ["I remember hearing it, but the source was indirect.","That source chain makes me less confident."],
 ["Would you repeat the claim to someone else?","Only as an unverified report, not as a fact."],
 ["The bakery still has its normal prices posted.","That evidence makes the giveaway less credible."],
 ["It is interesting how quickly the claim travelled.","Yes, even people who doubt it kept discussing it."]
];
let running=true,ticks=0,repeats=0,generation=0,lastSpread=-520,stepPending=false,sessionStopped=false,chatPending=false,chatCount=0,worldSyncPending=false;
const seenAutonomousConversations=new Set();
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function addLog(speaker,listener,text){const e=document.createElement("div");e.className="event";e.innerHTML=`<strong>${speaker} → ${listener}</strong>${text}`;document.querySelector("#log").prepend(e)}
function drawTown(w,h){ctx.fillStyle="#a9ce8d";ctx.fillRect(0,0,w,h);ctx.fillStyle="#d9cbb0";ctx.fillRect(0,h*.42,w,h*.15);ctx.fillRect(w*.43,0,w*.14,h);ctx.strokeStyle="#eee5d2";ctx.lineWidth=2;ctx.setLineDash([14,12]);ctx.beginPath();ctx.moveTo(0,h*.495);ctx.lineTo(w,h*.495);ctx.moveTo(w*.5,0);ctx.lineTo(w*.5,h);ctx.stroke();ctx.setLineDash([]);places.forEach(([name,x,y,pw,ph,color])=>{ctx.fillStyle="#0002";roundedRect(x*w+5,y*h+7,pw*w,ph*h,10);ctx.fill();ctx.fillStyle=color;roundedRect(x*w,y*h,pw*w,ph*h,10);ctx.fill();ctx.fillStyle="#f5e9d1";ctx.fillRect((x+.1)*w,(y+ph-.075)*h,.07*w,.075*h);ctx.fillStyle="#162136";ctx.font="700 11px Segoe UI";ctx.fillText(name,(x+.018)*w,(y+.038)*h)});for(let i=0;i<13;i++){ctx.fillStyle=i%2?"#5f8e58":"#76a56b";ctx.beginPath();ctx.arc((.025+i*.08)*w,(.035+(i%3)*.31)*h,7,0,Math.PI*2);ctx.fill()}}
function drawPerson(p,w,h){const x=p.x*w,y=p.y*h;ctx.fillStyle="#0002";ctx.beginPath();ctx.ellipse(x,y+19,17,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.shirt;roundedRect(x-12,y,24,28,7);ctx.fill();ctx.fillStyle=p.skin;ctx.beginPath();ctx.arc(x,y-9,11,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.hair;ctx.beginPath();ctx.arc(x,y-13,11,Math.PI,Math.PI*2);ctx.fill();if(p.name==="Bob"){ctx.fillStyle="white";ctx.beginPath();ctx.arc(x,y-17,12,Math.PI,Math.PI*2);ctx.fill()}if(p.name==="Charlie"){ctx.strokeStyle="#172033";ctx.lineWidth=1.5;ctx.strokeRect(x-8,y-12,7,5);ctx.strokeRect(x+1,y-12,7,5)}if(p.skeptical){ctx.strokeStyle="#244f7b";ctx.lineWidth=3;ctx.strokeRect(x-16,y-31,32,52)}if(p.knows){ctx.fillStyle="#fff";ctx.strokeStyle="#dd684d";ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+14,y-23,5,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.fillStyle="#172033";ctx.font="700 12px Segoe UI";ctx.textAlign="center";ctx.fillText(p.name,x,y+43);ctx.textAlign="left";if(p.speech&&ticks<p.bubbleUntil)drawBubble(p,x,y,w)}
function drawBubble(p,x,y,w){ctx.font="12px Segoe UI";const max=190,words=p.speech.split(" "),lines=[];let line="";words.forEach(word=>{const test=line+word+" ";if(ctx.measureText(test).width>max){lines.push(line);line=word+" "}else line=test});lines.push(line);const bw=Math.min(max+22,Math.max(...lines.map(v=>ctx.measureText(v).width))+22),bh=lines.length*16+18,bx=Math.max(8,Math.min(w-bw-8,x-bw/2)),by=y-58-bh;ctx.fillStyle="#fffdf8";ctx.strokeStyle=p.skeptical?"#4776a8":"#d85f49";ctx.lineWidth=2;roundedRect(bx,by,bw,bh,10);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x-7,by+bh);ctx.lineTo(x,by+bh+9);ctx.lineTo(x+7,by+bh);ctx.fill();ctx.stroke();ctx.fillStyle="#172033";lines.forEach((v,i)=>ctx.fillText(v.trim(),bx+11,by+18+i*16))}
function render(){document.querySelector("#exposed").textContent=people.filter(p=>p.knows).length;document.querySelector("#believers").textContent=people.filter(p=>p.believes).length;document.querySelector("#repeats").textContent=repeats;document.querySelector("#generation").textContent=generation;document.querySelector("#agents").innerHTML=people.map(p=>`<div class="agent" title="${p.decisionReason||"Waiting for world decision"}"><i class="dot" style="background:${p.shirt}"></i><span><b>${p.name}</b> · ${p.role} · ${p.activity||"idle"} (${p.decisionSource||"schedule"})${p.knows?" · exposed":""}</span><b class="${p.skeptical?"skeptic":""}">${p.skeptical?"SKEPTICAL":p.believes?"BELIEVES":"BASELINE"}</b></div>`).join("")}
function renderUsage(state){const usage=state.usage||{};document.querySelector("#api-calls").textContent=usage.calls||0;document.querySelector("#input-tokens").textContent=usage.input_tokens||0;document.querySelector("#output-tokens").textContent=usage.output_tokens||0;document.querySelector("#api-cost").textContent=`$${Number(usage.estimated_cost_usd||0).toFixed(4)}`}
async function conversation(){if(stepPending||sessionStopped)return;stepPending=true;lastSpread=ticks;try{const response=await fetch("/api/step",{method:"POST"}),payload=await response.json();if(!response.ok){sessionStopped=true;document.querySelector("#claim-status").textContent="PROPAGATION STOPPED";addLog("Python agent system","Town",payload.error);return}const turn=payload.turn,source=people.find(p=>p.name===turn.speaker),target=people.find(p=>p.name===turn.listener);source.speech=turn.message;target.speech=turn.reason;source.bubbleUntil=ticks+520;target.bubbleUntil=ticks+520;target.knows=true;target.believes=turn.believes_claim;if(turn.repeats_claim)repeats++;generation=turn.generation;document.querySelector("#claim-status").textContent=`ACTIVE CLAIM · GENERATION ${generation}`;const meetingX=(source.x+target.x)/2,meetingY=(source.y+target.y)/2;source.tx=Math.max(.1,meetingX-.025);source.ty=meetingY;target.tx=Math.min(.9,meetingX+.025);target.ty=meetingY;addLog(source.name,target.name,`${turn.message} ${target.name}'s model decision: ${turn.reason}`);render();if(!turn.repeats_claim){sessionStopped=true;document.querySelector("#claim-status").textContent=`STOPPED AT GENERATION ${generation}`}}catch(error){sessionStopped=true;addLog("API error","Town",error.message)}finally{stepPending=false}}
async function townChat(){if(chatPending||chatCount>=3)return;chatPending=true;lastSpread=ticks;try{const response=await fetch("/api/chat",{method:"POST"}),payload=await response.json();if(!response.ok){chatCount=3;addLog("Python agent system","Town",payload.error);return}const chat=payload.chat,source=people.find(p=>p.name===chat.speaker),target=people.find(p=>p.name===chat.listener);source.speech=chat.speaker_message;target.speech=chat.listener_reply;source.bubbleUntil=ticks+620;target.bubbleUntil=ticks+620;const meetingX=(source.x+target.x)/2,meetingY=(source.y+target.y)/2;source.tx=Math.max(.1,meetingX-.025);source.ty=meetingY;target.tx=Math.min(.9,meetingX+.025);target.ty=meetingY;chatCount=chat.chat_number;addLog(source.name,target.name,`${chat.speaker_message} ${target.name}: ${chat.listener_reply}`)}catch(error){chatCount=3;addLog("API error","Town",error.message)}finally{chatPending=false}}
async function connect(){try{const response=await fetch("/api/state"),state=await response.json();renderUsage(state);document.querySelector("#mode-label").textContent=state.mode==="live-ai"?"LIVE AI MODE":"FREE SIMULATION MODE";document.querySelector("#claim-status").textContent="ACTIVE CLAIM · GENERATION 0"}catch(error){document.querySelector("#claim-status").textContent="PYTHON CONNECTION FAILED"}}
async function refreshUsage(){try{const response=await fetch("/api/state"),state=await response.json();renderUsage(state)}catch(error){/* The main connection indicator handles server errors. */}}
function showAutonomousConversations(conversations){conversations.forEach(chat=>{const key=`${chat.minute}:${chat.speaker}:${chat.listener}`;if(seenAutonomousConversations.has(key))return;seenAutonomousConversations.add(key);const source=people.find(person=>person.name===chat.speaker);if(source){source.speech=chat.message;source.bubbleUntil=ticks+620}addLog(chat.speaker,chat.listener,chat.message)})}
async function syncWorld(){if(worldSyncPending)return;worldSyncPending=true;try{const response=await fetch(running?"/api/world/tick":"/api/world",{method:running?"POST":"GET"}),world=await response.json();clock.textContent=world.clock;people.forEach(person=>{const resident=world.residents[person.name];if(!resident)return;person.tx=resident.x;person.ty=resident.y;person.activity=resident.activity;person.decisionSource=resident.decision_source;person.decisionReason=resident.decision_reason});showAutonomousConversations(world.autonomous_conversations||[]);render()}catch(error){addLog("World API","Town",error.message)}finally{worldSyncPending=false}}
function update(){if(running){ticks++;people.forEach(p=>{p.x+=(p.tx-p.x)*.055;p.y+=(p.ty-p.y)*.055});if(!sessionStopped&&ticks-lastSpread>650)conversation();if(sessionStopped&&chatCount<3&&ticks-lastSpread>900)townChat()}const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);drawTown(w,h);people.forEach(p=>drawPerson(p,w,h));requestAnimationFrame(update)}
toggle.onclick=()=>{running=!running;toggle.textContent=running?"Pause":"Resume"};reset.onclick=()=>location.reload();window.onresize=resize;resize();render();addLog("Town system","Alice","Python-backed town session initialized.");connect();syncWorld();setInterval(refreshUsage,1000);setInterval(syncWorld,500);requestAnimationFrame(update);
