const canvas=document.querySelector("#town"),ctx=canvas.getContext("2d");
const people=[
 {name:"Alice",role:"Reporter",skin:"#8c563b",hair:"#31221d",shirt:"#d85f49",skeptical:false,x:.18,y:.72,knows:true,believes:false},
 {name:"Bob",role:"Baker",skin:"#d59a73",hair:"#5b3827",shirt:"#e4a43c",skeptical:true,x:.38,y:.26,knows:false,believes:false},
 {name:"Charlie",role:"Librarian",skin:"#704733",hair:"#15171c",shirt:"#4776a8",skeptical:false,x:.70,y:.28,knows:false,believes:false},
 {name:"Dana",role:"Planner",skin:"#c68662",hair:"#7d3f4f",shirt:"#815b91",skeptical:true,x:.78,y:.72,knows:false,believes:false}
];
people.forEach(p=>Object.assign(p,{tx:p.x,ty:p.y,speech:"",bubbleUntil:0}));
const places=[["SUNRISE BAKERY",.06,.06,.27,.21,"#d88761"],["MAPLE LIBRARY",.67,.06,.27,.21,"#718bad"],["TOWN HALL",.06,.66,.27,.21,"#cdb15f"],["BUS STOP",.69,.69,.22,.14,"#6f9569"]];
const messages=[
 ["I heard the bakery is giving away free bread today.","Interesting, but has anyone confirmed that?"],
 ["Alice said the bakery may have free bread.","I can mention it, but I do not know if it is true."],
 ["People are talking about a bakery giveaway.","I will remember it as an unverified report."]
];
let running=true,ticks=0,repeats=0,generation=0,lastSpread=-520;
function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio;canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}
function roundedRect(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function addLog(speaker,listener,text){const e=document.createElement("div");e.className="event";e.innerHTML=`<strong>${speaker} → ${listener}</strong>${text}`;document.querySelector("#log").prepend(e)}
function drawTown(w,h){ctx.fillStyle="#a9ce8d";ctx.fillRect(0,0,w,h);ctx.fillStyle="#d9cbb0";ctx.fillRect(0,h*.42,w,h*.15);ctx.fillRect(w*.43,0,w*.14,h);ctx.strokeStyle="#eee5d2";ctx.lineWidth=2;ctx.setLineDash([14,12]);ctx.beginPath();ctx.moveTo(0,h*.495);ctx.lineTo(w,h*.495);ctx.moveTo(w*.5,0);ctx.lineTo(w*.5,h);ctx.stroke();ctx.setLineDash([]);places.forEach(([name,x,y,pw,ph,color])=>{ctx.fillStyle="#0002";roundedRect(x*w+5,y*h+7,pw*w,ph*h,10);ctx.fill();ctx.fillStyle=color;roundedRect(x*w,y*h,pw*w,ph*h,10);ctx.fill();ctx.fillStyle="#f5e9d1";ctx.fillRect((x+.1)*w,(y+ph-.075)*h,.07*w,.075*h);ctx.fillStyle="#162136";ctx.font="700 11px Segoe UI";ctx.fillText(name,(x+.018)*w,(y+.038)*h)});for(let i=0;i<13;i++){ctx.fillStyle=i%2?"#5f8e58":"#76a56b";ctx.beginPath();ctx.arc((.025+i*.08)*w,(.035+(i%3)*.31)*h,7,0,Math.PI*2);ctx.fill()}}
function drawPerson(p,w,h){const x=p.x*w,y=p.y*h;ctx.fillStyle="#0002";ctx.beginPath();ctx.ellipse(x,y+19,17,6,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.shirt;roundedRect(x-12,y,24,28,7);ctx.fill();ctx.fillStyle=p.skin;ctx.beginPath();ctx.arc(x,y-9,11,0,Math.PI*2);ctx.fill();ctx.fillStyle=p.hair;ctx.beginPath();ctx.arc(x,y-13,11,Math.PI,Math.PI*2);ctx.fill();if(p.name==="Bob"){ctx.fillStyle="white";ctx.beginPath();ctx.arc(x,y-17,12,Math.PI,Math.PI*2);ctx.fill()}if(p.name==="Charlie"){ctx.strokeStyle="#172033";ctx.lineWidth=1.5;ctx.strokeRect(x-8,y-12,7,5);ctx.strokeRect(x+1,y-12,7,5)}if(p.skeptical){ctx.strokeStyle="#244f7b";ctx.lineWidth=3;ctx.strokeRect(x-16,y-31,32,52)}if(p.knows){ctx.fillStyle="#fff";ctx.strokeStyle="#dd684d";ctx.lineWidth=2;ctx.beginPath();ctx.arc(x+14,y-23,5,0,Math.PI*2);ctx.fill();ctx.stroke()}ctx.fillStyle="#172033";ctx.font="700 12px Segoe UI";ctx.textAlign="center";ctx.fillText(p.name,x,y+43);ctx.textAlign="left";if(p.speech&&ticks<p.bubbleUntil)drawBubble(p,x,y,w)}
function drawBubble(p,x,y,w){ctx.font="12px Segoe UI";const max=190,words=p.speech.split(" "),lines=[];let line="";words.forEach(word=>{const test=line+word+" ";if(ctx.measureText(test).width>max){lines.push(line);line=word+" "}else line=test});lines.push(line);const bw=Math.min(max+22,Math.max(...lines.map(v=>ctx.measureText(v).width))+22),bh=lines.length*16+18,bx=Math.max(8,Math.min(w-bw-8,x-bw/2)),by=y-58-bh;ctx.fillStyle="#fffdf8";ctx.strokeStyle=p.skeptical?"#4776a8":"#d85f49";ctx.lineWidth=2;roundedRect(bx,by,bw,bh,10);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(x-7,by+bh);ctx.lineTo(x,by+bh+9);ctx.lineTo(x+7,by+bh);ctx.fill();ctx.stroke();ctx.fillStyle="#172033";lines.forEach((v,i)=>ctx.fillText(v.trim(),bx+11,by+18+i*16))}
function render(){document.querySelector("#exposed").textContent=people.filter(p=>p.knows).length;document.querySelector("#believers").textContent=people.filter(p=>p.believes).length;document.querySelector("#repeats").textContent=repeats;document.querySelector("#generation").textContent=generation;document.querySelector("#agents").innerHTML=people.map(p=>`<div class="agent"><i class="dot" style="background:${p.shirt}"></i><span><b>${p.name}</b> · ${p.role}${p.knows?" · exposed":""}</span><b class="${p.skeptical?"skeptic":""}">${p.skeptical?"SKEPTICAL":p.believes?"BELIEVES":"BASELINE"}</b></div>`).join("")}
function conversation(){const source=[...people].reverse().find(p=>p.knows),target=people.find(p=>!p.knows);if(!source||!target)return;const pair=messages[Math.min(generation,messages.length-1)];source.speech=pair[0];target.speech=pair[1];source.bubbleUntil=ticks+430;target.bubbleUntil=ticks+430;target.knows=true;target.believes=!target.skeptical&&Math.random()>.52;source.tx=target.x;source.ty=target.y;target.tx=source.x;target.ty=source.y;repeats++;generation++;lastSpread=ticks;addLog(source.name,target.name,`${pair[0]} ${target.name}: “${pair[1]}”`);render()}
function update(){if(running){ticks++;people.forEach(p=>{if(Math.random()<.0015){p.tx=.12+Math.random()*.76;p.ty=.12+Math.random()*.76}p.x+=(p.tx-p.x)*.0022;p.y+=(p.ty-p.y)*.0022});if(ticks-lastSpread>650)conversation();clock.textContent=`DAY 01 · ${String(8+Math.floor(ticks/700)%12).padStart(2,"0")}:00`}const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);drawTown(w,h);people.forEach(p=>drawPerson(p,w,h));requestAnimationFrame(update)}
toggle.onclick=()=>{running=!running;toggle.textContent=running?"Pause":"Resume"};reset.onclick=()=>location.reload();window.onresize=resize;resize();render();addLog("Town system","Alice","Alice begins with an unverified bakery claim.");requestAnimationFrame(update);
